// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ucpr/mongo-streamer/internal/config"
	"github.com/ucpr/mongo-streamer/internal/mongo"
)

// Injectors from wire.go:

func inject(ctx context.Context) (*App, error) {
	mongoDB, err := config.NewMongoDB(ctx)
	if err != nil {
		return nil, err
	}
	client, err := mongo.NewClient(ctx, mongoDB)
	if err != nil {
		return nil, err
	}
	app := NewApp(client)
	return app, nil
}
