{
 "title": "mongo-streamer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "mongo-streamer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ChangeStream Received Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mongo_streamer_mongodb_change_stream_received_total",
     "legendFormat": "{{instance}} | {{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "ChangeStream event handled success total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "mongo_streamer_mongodb_change_stream_handle_event_success_total",
     "legendFormat": "{{instance}} | {{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "ChangeStream event handled failed total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mongo_streamer_mongodb_change_stream_handle_event_failed_total",
     "legendFormat": "{{instance}} | {{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "ChangeStream Received Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongo_streamer_mongodb_change_stream_received_bytes_total",
     "legendFormat": "{{instance}} | {{database}}.{{collection}}"
    }
   ]
  }
 ]
}